name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: python -m pip install -U pip
      - run: python -m pip install -e .
      - run: |
          aigym validate examples/manifest/minimal.yaml
          aigym compare  examples/manifest/minimal.yaml examples/manifest/transformer.yaml
          aigym calibrate --baseline configs/apm/baseline.yaml \
            --left examples/manifest/minimal.yaml \
            --right examples/manifest/transformer.yaml \
            --out runs/calibration.json
