name: CI
on:
  push:
  pull_request:

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -e .
          pip install pyyaml

      - name: Validate example manifests
        run: |
          for file in $(find examples -name "*.yaml"); do
            echo "Validating $file"
            aigym validate "$file"
          done
